//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public int articleId { get; set; }
        public string articleImage { get; set; }
        public string caption { get; set; }
        public string articleDescription { get; set; }
        public string articleAuthor { get; set; }
        public string articleDate { get; set; }
        public string authorimg { get; set; }
        public string articleDetail { get; set; }
    }
}
