//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recentNew
    {
        public int newsId { get; set; }
        public string newsDescription { get; set; }
        public string newsDate { get; set; }
        public string newsImage { get; set; }
        public string newsDetail { get; set; }
    }
}
